### ISSUE TITLE
Romanian missing from 2021 State of CSS survey

### ISSUE THREAD

**Issue by magdaavram** [Devographics/locale-ro-RO#1]
Hey, @SachaG!
I want to contribute on this year’s survey as well. 
I’ve seen that Romanian translations are missing for the 2021 State of CSS survey. Is that only because there’s no translation for the homepage intro (the ‘state_of_css_2021_survey’ file)?
Thanks!

**Comment by SachaG** [comment]
I used the files from last year as a starting point so any content that is new for 2021 will not have been translated yet. It would be really great if you could help! I'll give you rights to this repo.

**Comment by magdaavram** [comment]
Thanks, @SachaG! I've opened a PR with the 2021 file. Please review when you're available.

**Comment by magdaavram** [comment]
Hey, @SachaG! Is there anything missing or do we have everything in place to also publish the Romanian version?
